---
title: "project 2"
author: "Keiryn Hart, 300428418"
date: "12/10/2020"
output: html_document
---

```{r}
library(timetk)
library(lubridate)
library(zoo)
library(data.table)  
library(dplyr)
library(tidyr)
library(gridExtra)
library(fitdistrplus)

victims <- read.csv('/Users/keirynhart/Documents/Uni/Data 301/DATA301-Group-Project/Data/Victimisations_time_and_place (cleaned).csv')
covid <- read.csv("/Users/keirynhart/Documents/Uni/Data 301/DATA301-Group-Project/Data/Covid calls for service cleaned.csv")
total <- read.csv('/Users/keirynhart/Documents/Uni/Data 301/DATA301-Group-Project/Data/merged data (Final).csv')
victims2020 <- read.csv("/Users/keirynhart/Documents/Uni/Data 301/Project/victimizations-2020.csv", stringsAsFactors = FALSE)
merge <- read.csv("/Users/keirynhart/Documents/Uni/Data 301/Project/merged data (Final).csv")
```



```{r}
covid[, "Location"] <- NA

for(i in 1:nrow(covid)){
  if(covid$District[i] == "Auckland City" | covid$District[i] == "Counties/Manukau" | covid$District[i] == "Waitemata"){
    covid$Location[i] <- "Auckland"
  }
  else if(covid$District[i] == "Bay Of Plenty"){
    covid$Location[i] <- "Bay Of Plenty"
  }
  else if(covid$District[i] == "Waikato"){
    covid$Location[i] <- "Waikato"
  }
  else if(covid$District[i] == "Eastern"){
    covid$Location[i] <- "Hawkes Bay/ Gisborne"
  }
  else if(covid$District[i] == "Central"){
    covid$Location[i] <- "West Coast/ Upper-Central North"
  }
  else if(covid$District[i] == "Wellington"){
    covid$Location[i] <- "Wellington/ Lower-Central North"
  }
  else if(covid$District[i] == "Tasman"){
    covid$Location[i] <- "Tasman/ South-West Coast"
  }
  else if(covid$District[i] == "Northland"){
    covid$Location[i] <- "Northland"
  }
  else if(covid$District[i] == "Southern"){
    covid$Location[i] <- "Southland/ Otago"
  }
  else if(covid$District[i] == "Canterbury"){
    covid$Location[i] <- "Cantebury"
  }
  else{covid$Location[i] <- "Other"}
}


covid[,c("X", "District", "Calls.for.Service.and.Prevention", "Crime.and.NonCrime.Demand", "Event.Category")] <- NULL

level_sum <- covid %>% group_by(Location, Alert.Level) %>% summarise(Number = sum(No))

level_sum <- level_sum %>% filter(Location != 'Other')
```


```{r}
library(ggplot2)

ggplot(data = covid, aes(x = Event.Type, y = No)) + geom_bar(stat='identity')

ggplot(data = covid, aes(x = Location, y = No)) + geom_bar(stat='identity')

unique(covid$Location)

level_sum$Alert.Level <- as.character(level_sum$Alert.Level)

ggplot(level_sum, aes(fill = Alert.Level, y=Number, x=Location)) + geom_bar(aes(fill=Alert.Level), position="dodge", stat="identity") + theme(axis.text.x = element_text(angle = 90))


```


```{r}
victims[, "Location"] <- NA

for(i in 1:nrow(victims)){
  if(victims$Territorial.Authority[i] == "Auckland."){
    victims$Location[i] <- "Auckland"
  }
  else if(victims$Territorial.Authority[i] == "Far North District." | victims$Territorial.Authority[i] == "Whangarei District." | victims$Territorial.Authority[i] == "Kaipara District."){
    victims$Location[i] <- "Northland"
  }
  else if(victims$Territorial.Authority[i] == "Waipa District." | victims$Territorial.Authority[i] == "Hamilton City." | victims$Territorial.Authority[i] == "Taupo District." | victims$Territorial.Authority[i] == "Hauraki District." | victims$Territorial.Authority[i] == "Otorohanga District." | victims$Territorial.Authority[i] == "South Waikato District." | victims$Territorial.Authority[i] == "Thames-Coromandel District." | victims$Territorial.Authority[i] == "Waitomo District." | victims$Territorial.Authority[i] == "Waikato District." | victims$Territorial.Authority[i] == "Matamata-Piako District."){
    victims$Location[i] <- "Waikato"
  }
  else if(victims$Territorial.Authority[i] == "Whakatane District." | victims$Territorial.Authority[i] == "Opotiki District." | victims$Territorial.Authority[i] == "Kawerau District." | victims$Territorial.Authority[i] == "Tauranga City." | victims$Territorial.Authority[i] == "Rotorua District." | victims$Territorial.Authority[i] == "Western Bay of Plenty District."){
    victims$Location[i] <- "Bay Of Plenty"
  }
  else if(victims$Territorial.Authority[i] == "Napier City." | victims$Territorial.Authority[i] == "Central Hawke's Bay District." | victims$Territorial.Authority[i] == "Hastings District." | victims$Territorial.Authority[i] == "Gisborne District." | victims$Territorial.Authority[i] == "Wairoa District."){
    victims$Location[i] <- "Hawkes Bay/ Gisborne"
  }
  else if(victims$Territorial.Authority[i] == "South Taranaki District." | victims$Territorial.Authority[i] == "Stratford District." | victims$Territorial.Authority[i] == "Ruapehu District." | victims$Territorial.Authority[i] == "Rangitikei District." | victims$Territorial.Authority[i] == "New Plymouth District." | victims$Territorial.Authority[i] == "Manawatu District." | victims$Territorial.Authority[i] == "Wanganui District." | victims$Territorial.Authority[i] == "Palmerston North City."){
    victims$Location[i] <- "West Coast/ Upper-Central North"
  }
  else if(victims$Territorial.Authority[i] == "Masterton District." | victims$Territorial.Authority[i] == "South Wairarapa District." | victims$Territorial.Authority[i] == "Lower Hutt City." | victims$Territorial.Authority[i] == "Porirua City." | victims$Territorial.Authority[i] == "Kapiti Coast District." | victims$Territorial.Authority[i] == "Horowhenua District." | victims$Territorial.Authority[i] == "Wellington City."  | victims$Territorial.Authority[i] == "Tararua District." | victims$Territorial.Authority[i] == "Carterton District." | victims$Territorial.Authority[i] == "Upper Hutt City."){
    victims$Location[i] <- "Wellington/ Lower-Central North"
  }
  else if(victims$Territorial.Authority[i] == "Grey District." | victims$Territorial.Authority[i] == "Buller District." | victims$Territorial.Authority[i] == "Tasman District." | victims$Territorial.Authority[i] == "Marlborough District." | victims$Territorial.Authority[i] == "Westland District." | victims$Territorial.Authority[i] == "Nelson City."){
    victims$Location[i] <- "Tasman/ South-West Coast"
  }
  else if(victims$Territorial.Authority[i] == "Invercargill City." | victims$Territorial.Authority[i] == "Queenstown-Lakes District." | victims$Territorial.Authority[i] == "Southland District." | victims$Territorial.Authority[i] == "Central Otago District." | victims$Territorial.Authority[i] == "Gore District." | victims$Territorial.Authority[i] == "Clutha District." | victims$Territorial.Authority[i] == "Dunedin City."){
    victims$Location[i] <- "Southland/ Otago"
  }
  else{victims$Location[i] <- "Canterbury"}
  }


#write.csv(victims,"/Users/keirynhart/Documents/Uni/Data 301/Project/victimizations.csv")
#write.csv(covid,"/Users/keirynhart/Documents/Uni/Data 301/Project/covid.csv")
```



```{r}
victims2020[, "Location"] <- NA

for(i in 1:nrow(victims2020)){
  if(victims2020$Territorial.Authority[i] == "Auckland."){
    victims2020$Location[i] <- "Auckland"
  }
  else if(victims2020$Territorial.Authority[i] == "Far North District." | victims2020$Territorial.Authority[i] == "Whangarei District." | victims2020$Territorial.Authority[i] == "Kaipara District."){
    victims2020$Location[i] <- "Northland"
  }
  else if(victims2020$Territorial.Authority[i] == "Waipa District." | victims2020$Territorial.Authority[i] == "Hamilton City." | victims2020$Territorial.Authority[i] == "Taupo District." | victims2020$Territorial.Authority[i] == "Hauraki District." | victims2020$Territorial.Authority[i] == "Otorohanga District." | victims2020$Territorial.Authority[i] == "South Waikato District." | victims2020$Territorial.Authority[i] == "Thames-Coromandel District." | victims2020$Territorial.Authority[i] == "Waitomo District." | victims2020$Territorial.Authority[i] == "Waikato District." | victims2020$Territorial.Authority[i] == "Matamata-Piako District."){
    victims2020$Location[i] <- "Waikato"
  }
  else if(victims2020$Territorial.Authority[i] == "Whakatane District." | victims2020$Territorial.Authority[i] == "Opotiki District." | victims2020$Territorial.Authority[i] == "Kawerau District." | victims2020$Territorial.Authority[i] == "Tauranga City." | victims2020$Territorial.Authority[i] == "Rotorua District." | victims2020$Territorial.Authority[i] == "Western Bay of Plenty District."){
    victims2020$Location[i] <- "Bay Of Plenty"
  }
  else if(victims2020$Territorial.Authority[i] == "Napier City." | victims2020$Territorial.Authority[i] == "Central Hawke's Bay District." | victims2020$Territorial.Authority[i] == "Hastings District." | victims2020$Territorial.Authority[i] == "Gisborne District." | victims2020$Territorial.Authority[i] == "Wairoa District."){
    victims2020$Location[i] <- "Hawkes Bay/ Gisborne"
  }
  else if(victims2020$Territorial.Authority[i] == "South Taranaki District." | victims2020$Territorial.Authority[i] == "Stratford District." | victims2020$Territorial.Authority[i] == "Ruapehu District." | victims2020$Territorial.Authority[i] == "Rangitikei District." | victims2020$Territorial.Authority[i] == "New Plymouth District." | victims2020$Territorial.Authority[i] == "Manawatu District." | victims2020$Territorial.Authority[i] == "Wanganui District." | victims2020$Territorial.Authority[i] == "Palmerston North City."){
    victims2020$Location[i] <- "West Coast/ Upper-Central North"
  }
  else if(victims2020$Territorial.Authority[i] == "Masterton District." | victims2020$Territorial.Authority[i] == "South Wairarapa District." | victims2020$Territorial.Authority[i] == "Lower Hutt City." | victims2020$Territorial.Authority[i] == "Porirua City." | victims2020$Territorial.Authority[i] == "Kapiti Coast District." | victims2020$Territorial.Authority[i] == "Horowhenua District." | victims2020$Territorial.Authority[i] == "Wellington City."  | victims2020$Territorial.Authority[i] == "Tararua District." | victims2020$Territorial.Authority[i] == "Carterton District." | victims2020$Territorial.Authority[i] == "Upper Hutt City."){
    victims2020$Location[i] <- "Wellington/ Lower-Central North"
  }
  else if(victims2020$Territorial.Authority[i] == "Grey District." | victims2020$Territorial.Authority[i] == "Buller District." | victims2020$Territorial.Authority[i] == "Tasman District." | victims2020$Territorial.Authority[i] == "Marlborough District." | victims2020$Territorial.Authority[i] == "Westland District." | victims2020$Territorial.Authority[i] == "Nelson City."){
    victims2020$Location[i] <- "Tasman/ South-West Coast"
  }
  else if(victims2020$Territorial.Authority[i] == "Invercargill City." | victims2020$Territorial.Authority[i] == "Queenstown-Lakes District." | victims2020$Territorial.Authority[i] == "Southland District." | victims2020$Territorial.Authority[i] == "Central Otago District." | victims2020$Territorial.Authority[i] == "Gore District." | victims2020$Territorial.Authority[i] == "Clutha District." | victims2020$Territorial.Authority[i] == "Dunedin City."){
    victims2020$Location[i] <- "Southland/ Otago"
  }
  else{victims2020$Location[i] <- "Canterbury"}
}

```


```{r}
victims2020[,c("X", "Table.1", "ANZSOC.Division", "ANZSOC.Subdivision", "Location.Type", "Locn.Type.Division", "Weapon")] <- NULL

victims$date <- as.Date(victims$date, format = "%d/%m/%y")

#converting months
victims2020 <- victims2020 %>% mutate(month=recode(month, 
                         "Feb" = 02, "Mar" = 03, "Apr" = 04, "May" = 05, "Jun" = 06, "Jul" = 07, "Aug" = 08))
#converting year
victims2020 <- victims2020 %>% mutate(year=recode(year, "20" = 2020))

#combining the two
victims2020 <- within(victims2020, date <- sprintf("%d-%d", year, month))

#date
victims2020$date <- as.Date(as.yearmon(victims2020$date), format = "%y-%m")

#counting number of victimizations per location and date:
victims <- count(victims, Location, date) %>% ungroup()
victims2020 <- count(victims2020, Location, date) %>% ungroup()


#splitting back into month and year:
victims1 <- separate(victims, "date", c("year", "month")) 
victims20 <- separate(victims2020, "date", c("year", "month"))

#name change:
victims1 <- victims1 %>% rename(Number = n)
victims20 <- victims20 %>% rename(Number = n)

victims_full <- rbind(victims1, victims20)

#write.csv(victims_full,"/Users/keirynhart/Documents/Uni/Data 301/Project/victimizations_concise.csv")

```


```{r}
victims17 <- filter(victims1, year == '2017')
victims18 <- filter(victims1, year == '2018')
victims19 <- filter(victims1, year == '2019')

victims17$month <- as.numeric(victims17$month)
```


```{r}
seven <- ggplot() + geom_line(data = victims17, aes(x = as.numeric(month), y = Number, color = Location)) + scale_x_continuous(breaks=seq(0, 12, by = 1)) + ggtitle("Rate of Assaults in 2017 by Location") + xlab("Month")
eight <- ggplot() + geom_line(data = victims18, aes(x = as.numeric(month), y = Number, color = Location)) + scale_x_continuous(breaks=seq(0, 12, by = 1)) + ggtitle("Rate of Assaults in 2018 by Location") + xlab("Month")
nine <- ggplot() + geom_line(data = victims19, aes(x = as.numeric(month), y = Number, color = Location)) + scale_x_continuous(breaks=seq(0, 12, by = 1)) + ggtitle("Rate of Assaults in 2019 by Location") + xlab("Month")
twenty <- ggplot() + geom_line(data = victims20, aes(x = as.numeric(month), y = Number, color = Location)) + scale_x_continuous(breaks=seq(0, 12, by = 1)) + ggtitle("Rate of Assaults in 2020 by Location") + xlab("Month")

seven
eight
nine
twenty
```



```{r}
hist(victims_full$Number, xlab = "Number of Cases", main = "Histogram of Number of Cases")
```


```{r}
library(fitdistrplus)

plot(fitdist(victims_full$Number, distr = "gamma", method = "mle"))
```

Locational Analysis:

```{r}
library(tmap)
library(spData)

map_nz = tm_shape(nz) + tm_polygons()
```


```{r}
total <- merge
total[,"Event"] <- NULL
agg <- aggregate(. ~ year + Alert.Level + Location, total, sum)
a <- 17
b <- 18
c <- 19
d <- 20

#name changes
agg$Location[agg$Location == "Wellington/ Lower-Central North"] <- "Wellington"
agg$Location[agg$Location == "Bay Of Plenty"] <- "Bay of Plenty"
agg$Location[agg$Location == "Cantebury"] <- "Canterbury"


nz$Name[nz$Name == "Manawatu-Wanganui"] <- "West Coast/ Upper-Central North"
nz$Name[nz$Name == "Hawke's Bay"] <- "Hawkes Bay/ Gisborne"
nz$Name[nz$Name == "Gisborne"] <- "Hawkes Bay/ Gisborne"
nz$Name[nz$Name == "Taranaki"] <- "West Coast/ Upper-Central North"
nz$Name[nz$Name == "Otago"] <- "Southland/ Otago"
nz$Name[nz$Name == "Southland"] <- "Southland/ Otago"
nz$Name[nz$Name == "Marlborough"] <- "Tasman/ South-West Coast"
nz$Name[nz$Name == "Tasman"] <- "Tasman/ South-West Coast"
nz$Name[nz$Name == "Nelson"] <- "Tasman/ South-West Coast"
nz$Name[nz$Name == "West Coast"] <- "Tasman/ South-West Coast"


seventeen <- subset(agg, year %in% a)
eighteen <- subset(agg, year %in% b)
nineteen <- subset(agg, year %in% c)
twenty <- subset(agg, year %in% d)

#seventeen
seventeen2 <- subset(seventeen, Alert.Level %in% 2)
seventeen3 <- subset(seventeen, Alert.Level %in% 3)
seventeen4 <- subset(seventeen, Alert.Level %in% 4)

#eighteen
eighteen2 <- subset(eighteen, Alert.Level %in% 2)
eighteen3 <- subset(eighteen, Alert.Level %in% 3)
eighteen4 <- subset(eighteen, Alert.Level %in% 4)

#nineteen
nineteen2 <- subset(nineteen, Alert.Level %in% 2)
nineteen3 <- subset(nineteen, Alert.Level %in% 3)
nineteen4 <- subset(nineteen, Alert.Level %in% 4)

#twenty
twentylvl2 <- subset(twenty, Alert.Level %in% 2)
twentylvl3 <- subset(twenty, Alert.Level %in% 3)
twentylvl4 <- subset(twenty, Alert.Level %in% 4)


twentylvl4<- twentylvl4[-6,] 

#seventeen
seventeen2 <- seventeen2[, c("Number.of.Victimizations", "Location")]
seventeen3 <- seventeen3[, c("Number.of.Victimizations", "Location")]
seventeen4 <- seventeen4[, c("Number.of.Victimizations", "Location")]
#eighteen
eighteen2 <- eighteen2[, c("Number.of.Victimizations", "Location")]
eighteen3 <- eighteen3[, c("Number.of.Victimizations", "Location")]
eighteen4 <- eighteen4[, c("Number.of.Victimizations", "Location")]
#nineteen
nineteen2 <- nineteen2[, c("Number.of.Victimizations", "Location")]
nineteen3 <- nineteen3[, c("Number.of.Victimizations", "Location")]
nineteen4 <- nineteen4[, c("Number.of.Victimizations", "Location")]
#twenty
twentylvl2 <- twentylvl2[, c("Number.of.Victimizations", "Location")]
twentylvl3 <- twentylvl3[, c("Number.of.Victimizations", "Location")]
twentylvl4 <- twentylvl4[, c("Number.of.Victimizations", "Location")]

#column name changes

#seventeen
names(seventeen2)[names(seventeen2) == "Number.of.Victimizations"] <- "2017 level 2 Equivalent"
names(seventeen3)[names(seventeen3) == "Number.of.Victimizations"] <- "2017 level 3 Equivalent"
names(seventeen4)[names(seventeen4) == "Number.of.Victimizations"] <- "2017 level 4 Equivalent"

#eighteen
names(eighteen2)[names(eighteen2) == "Number.of.Victimizations"] <- "2018 level 2 Equivalent"
names(eighteen3)[names(eighteen3) == "Number.of.Victimizations"] <- "2018 level 3 Equivalent"
names(eighteen4)[names(eighteen4) == "Number.of.Victimizations"] <- "2018 level 4 Equivalent"

#nineteen
names(nineteen2)[names(nineteen2) == "Number.of.Victimizations"] <- "2019 level 2 Equivalent"
names(nineteen3)[names(nineteen3) == "Number.of.Victimizations"] <- "2019 level 3 Equivalent"
names(nineteen4)[names(nineteen4) == "Number.of.Victimizations"] <- "2019 level 4 Equivalent"

#twenty
names(twentylvl2)[names(twentylvl2) == "Number.of.Victimizations"] <- "2020 level 2"
names(twentylvl3)[names(twentylvl3) == "Number.of.Victimizations"] <- "2020 level 3"
names(twentylvl4)[names(twentylvl4) == "Number.of.Victimizations"] <- "2020 level 4"

```



```{r}
nz <- dplyr::left_join(nz, seventeen2, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, seventeen3, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, seventeen4, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, eighteen2, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, eighteen3, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, eighteen4, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, nineteen2, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, nineteen3, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, nineteen4, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, twentylvl2, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, twentylvl3, by = c("Name" = "Location"))
nz <- dplyr::left_join(nz, twentylvl4, by = c("Name" = "Location"))


breaks <- c(0, 10, 20, 30, 40, 50, 100, 150, 200)


m1 <- tm_shape(nz) + tm_polygons(col = "2017 level 2 Equivalent", breaks = breaks) 
m2 <- tm_shape(nz) + tm_polygons(col = "2017 level 3 Equivalent", breaks = breaks)
m3 <- tm_shape(nz) + tm_polygons(col = "2017 level 4 Equivalent", breaks = breaks)
m4 <- tm_shape(nz) + tm_polygons(col = "2018 level 2 Equivalent", breaks = breaks)
m5 <- tm_shape(nz) + tm_polygons(col = "2018 level 3 Equivalent", breaks = breaks)
m6 <- tm_shape(nz) + tm_polygons(col = "2018 level 4 Equivalent", breaks = breaks)
m7 <- tm_shape(nz) + tm_polygons(col = "2019 level 2 Equivalent", breaks = breaks)
m8 <- tm_shape(nz) + tm_polygons(col = "2019 level 3 Equivalent", breaks = breaks)
m9 <- tm_shape(nz) + tm_polygons(col = "2019 level 4 Equivalent", breaks = breaks)
m10 <- tm_shape(nz) + tm_polygons(col = "2020 level 2", breaks = breaks)
m11 <- tm_shape(nz) + tm_polygons(col = "2020 level 3", breaks = breaks)
m12 <- tm_shape(nz) + tm_polygons(col = "2020 level 4", breaks = breaks)




tmap_arrange(m1, m2, m3,nrow = 1, ncol = 3)
tmap_arrange(m4,m5,m6, nrow = 1, ncol = 3)
tmap_arrange(m7,m8,m9, nrow = 1, ncol = 3)
tmap_arrange(m10,m11,m12, nrow = 1, ncol = 3)
```


```{r}

```

